### ISSUE TITLE
Add "reset()" method to all the trackers

### ISSUE THREAD

**Issue by Joilence** [mikel-brostrom/boxmot#1461]
Thanks for your work in the first place!

### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Add a `reset()` method to all the trackers (BYTETracker, BoTSORT, etc) to initialize the state again to be ready to perform tracking on a new sequence of detections.

### Use case

Use a single tracker instance to perform tracking on multiple independent sequence without initiate a new instance, which would help keep code clean sometimes.

```python
tracker = BYTETracker()

for seq_dets in seq_dets_list:
    tracker.reset()
    # tracker.update() for dets of each frame
```

Right now my workaround is to write a function for each tracker I want to use.

```python
def get_byte_tracker():
    return BYTETracker()

for seq_dets in seq_dets_list:
    tracker = get_byte_tracker()
    # tracker.update() for dets of each frame
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

Just want to confirm if it's something wanted in general; if so, I could submit a PR.

**Comment by mikel-brostrom** [comment]
This would be awesome @Joilence . Looking forward to the PR  🔥
