### ISSUE TITLE
Question about Evaluation on First 10 Frames

### ISSUE THREAD

**Issue by YoungjaeDev** [mikel-brostrom/boxmot#1464]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello,

I noticed in the benchmark notes that the evaluation was performed using only the first 10 frames of each MOT17 sequence. Could you please explain the rationale behind this decision? Specifically, I am curious to understand

1. Why only the first 10 frames were chosen for evaluation instead of using the entire sequence.
2. What benefits or insights are gained by limiting the evaluation to these initial frames.
3. Whether there are any plans to extend the evaluation to include more frames or the entire sequences in future assessments.

Thank you for your time and clarification!

**Comment by YoungjaeDev** [comment]
@mikel-brostrom 

The `--eval-existing` option seems to have disappeared again, any idea how it was replaced?

**Comment by mikel-brostrom** [comment]
> Why only the first 10 frames were chosen for evaluation instead of using the entire sequence.

The only reason is the lack of time

> What benefits or insights are gained by limiting the evaluation to these initial frames.

Nothing

> Whether there are any plans to extend the evaluation to include more frames or the entire sequences in future assessments

I am planning to implement a new evaluation method based on `pymotmetrics`. In this process I will also run full evaluations
