### ISSUE TITLE
 How do I keep track in low frame rate video？

### ISSUE THREAD

**Issue by LXXIANG12** [mikel-brostrom/boxmot#1505]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Due to the limitation of my device, frame loss occurs when I obtain RTSP video stream. When I test the tracking effect by using the video after frame loss, I find that many targets cannot be tracked, which is very serious. But when I saved a single video without losing frames to test, the tracking worked better. How do I handle this frame drop?

**Comment by mikel-brostrom** [comment]
You could start by modifying the process noise covariance like explained here:

https://github.com/mikel-brostrom/boxmot/pull/1484
