### ISSUE TITLE
AttributeError: 'BYTETracker' object has no attribute 'reset'

### ISSUE THREAD

**Issue by Czeni1** [mikel-brostrom/boxmot#1509]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello, I am using bytetrack, but when running this track.py file, I encountered this error. In track.py, I only changed the tracking algorithm to bytrtrack and did not make any other changes. Can you help me analyze what the reason is? thank you
![Uploading 9687616b3024b4e7fd17903cd046f62.png…]()

**Comment by mikel-brostrom** [comment]
Image is broken
