### ISSUE TITLE
train a REID MODEL

### ISSUE THREAD

**Issue by mj-Liusirs** [mikel-brostrom/boxmot#1522]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

HI,could you tell me how to train an reid model please?

**Comment by mikel-brostrom** [comment]
ReID model training is not available in this repo yet. This may help you meanwhile: https://kaiyangzhou.github.io/deep-person-reid/user_guide.html
