### ISSUE TITLE
How to combine ocsort and other algorithms you provide with yolov8?

### ISSUE THREAD

**Issue by lmaple24327** [mikel-brostrom/boxmot#1523]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

The tracking algorithm is specified in the yolov8 algorithm code, but I hope that in combination with these very good tracking algorithms provided by you, can you provide some ideas? 
Looking forward to your reply, thank you very much.

**Comment by mikel-brostrom** [comment]
Please reformulate your question. I cannot understand what you mean. Combine with what and for what reason?
