### ISSUE TITLE
StrongSORT plotting results

### ISSUE THREAD

**Issue by rayruchira** [mikel-brostrom/boxmot#1525]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

When trying to plot results for StrongSORT I get the error 

`AttributeError: 'StrongSORT' object has no attribute 'plot_results'`

Is it because it is not extending the `BaseTracker` class [here](https://github.com/mikel-brostrom/boxmot/blob/ff548d59de9236ce04c989b91d5c680a45b14abf/boxmot/trackers/strongsort/strong_sort.py#L14C18-L14C24)?

**Comment by lmaple24327** [comment]
> ### Search before asking
> * [x]  I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.
> 
> ### Question
> When trying to plot results for StrongSORT I get the error
> 
> `AttributeError: 'StrongSORT' object has no attribute 'plot_results'`
> 
> Is it because it is not extending the `BaseTracker` class [here](https://github.com/mikel-brostrom/boxmot/blob/ff548d59de9236ce04c989b91d5c680a45b14abf/boxmot/trackers/strongsort/strong_sort.py#L14C18-L14C24)?
Hello, do you know how to combine yolov8 with ocsort?

**Comment by JiaDongZou** [comment]
i think so

**Comment by JiaDongZou** [comment]
StrongSORT has no methon like plot_results

**Comment by JiaDongZou** [comment]
StrongSORT has no method like plot_results
