### ISSUE TITLE
it can't run when i start tracking

### ISSUE THREAD

**Issue by Edward-YS** [mikel-brostrom/boxmot#1564]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

when i run track.py,it remind me that --AttributeError: 'BoTSORT' object has no attribute 'reset'--
what's wrong?
Thank you for your help!

**Comment by davide-bontempelli-zupit** [comment]
@Edward-YS how did you fix this?

**Comment by mikel-brostrom** [comment]
Start with a clean installation. This error usually arises because you have not installed the yolo dependencies correctly. Follow the readme
