### ISSUE TITLE
Disable ReID module

### ISSUE THREAD

**Issue by setarekhosravi** [mikel-brostrom/boxmot#1571]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi, Thank you for your great work, I want to disable the ReID module and then evaluate the trackers, I want to compare the evaluation results of trackers with ReID and without ReID on my own dataset. How can I do it?

**Comment by setarekhosravi** [comment]
For example, for the HybridSORT tracker I used the official repository to evaluate tracking results when the ReID module is disabled, but I want to know if there is another way to use your repository.

**Comment by mikel-brostrom** [comment]
Deactivating ReID is not available for HybridSORT. You would need to toggle that functionality out

**Comment by setarekhosravi** [comment]
Okay Thank you.

**Comment by wk565** [comment]
> Deactivating ReID is not available for HybridSORT. You would need to toggle that functionality out

However， the original HybridSort has two versions: with REID and without REID.
