### ISSUE TITLE
Using different Reid models to evaluate DeepOcsort, but getting the same evaluation results

### ISSUE THREAD

**Issue by shixinwang00** [mikel-brostrom/boxmot#1573]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi,I'm using different Reid models to evaluate DeepOcsort, but getting the same evaluation results？
The command is as follows:
**Osnet**
`python3 tracking/val.py --benchmark MOT17-mini --yolo-model yolov8s.pt --reid-model tracking/weights/osnet_x0_25_msmt17.pt --tracking-method deepocsort --verbose --source ./assets/MOT17-mini/train`
_"HOTA": 39.228, "MOTA": 20.755, "IDF1": 36.122_
**Clip**
`python3 tracking/val.py --benchmark MOT17-mini --yolo-model yolov8s.pt --reid-model tracking/weights/clip_market1501.pt --tracking-method deepocsort --verbose --source ./assets/MOT17-mini/train`
_"HOTA": 39.228, "MOTA": 20.755, "IDF1": 36.122_

**Comment by mikel-brostrom** [comment]
`MOT17-mini` is comprised of 2 sequences with very few frames each. So chances that the ReID having any effect are minimal. Try on MOT17

**Comment by shixinwang00** [comment]
I re-evaluated on the MOT17, and the results obtained using the two ReID models are indeed different. Thank you very much!

**Comment by yaoshanliang** [comment]
Same question. 
I tried each reid model on my custom dataset with 20 clips. However, the results are same using different reid models. Any potential issues on my dataset?

```
--reid-model clip_market1501.pt
--reid-model osnet_x0_25_msmt17.pt
```

**Comment by mikel-brostrom** [comment]
Could be that you dataset is too "easy" for the ReID model to make ay difference
