### ISSUE TITLE
PyTorch version automatic update

### ISSUE THREAD

**Issue by wk565** [mikel-brostrom/boxmot#1574]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello , when I was configuring the environment, I found that boxmot would delete my previous old versions of pytorch (1.10.0) and torchvision (0.11.1). Is there any way to prevent them from upgrading?

**Comment by mikel-brostrom** [comment]
Create a specific environment for this repo

**Comment by wk565** [comment]
ok,thanks
