### ISSUE TITLE
Evaluation using bytetrack

### ISSUE THREAD

**Issue by wk565** [mikel-brostrom/boxmot#1575]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Bytetrack does not need to use the reid model, but I found that val.py must use the reid model, otherwise it will report an error as follows. The code command is 'python3 tracking/val.py --benchmark MOT17      --yolo-model yolov8n.pt --tracking-method bytetrack    --verbose --source ./tracking/val_utils/data/MOT17/train'

<img width="857" alt="image" src="https://github.com/user-attachments/assets/be73c148-923c-4c44-86dd-fe0e4f3f7fe7">

**Comment by mikel-brostrom** [comment]
Just add a reid model argument. The embeddings will be ignored for bytetrack
