### ISSUE TITLE
Why does the frame id of the txt file generated by the evaluation start at 2

### ISSUE THREAD

**Issue by microchila** [mikel-brostrom/boxmot#1578]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evaluation

### Bug

2,100,1337,420,171,369,1,0,0.878290
2,101,582,445,91,261,1,0,0.843291
2,102,1450,433,150,332,1,0,0.799683
2,103,441,444,114,275,1,0,0.759766
2,104,731,470,34,97,1,0,0.647027
2,105,1253,440,38,106,1,0,0.578172
3,100,1342,418,171,370,1,0,0.870906
3,101,582,445,91,261,1,0,0.846484
3,102,1450,436,150,331,1,0,0.796228
3,103,441,445,114,274,1,0,0.804655
3,104,731,472,34,96,1,0,0.662688
3,105,1254,439,38,107,1,0,0.521978
4,100,1346,418,174,376,1,0,0.873021
4,101,583,445,91,261,1,0,0.835983
4,102,1460,434,150,333,1,0,0.738290
4,103,441,445,114,275,1,0,0.756504
4,104,732,472,33,94,1,0,0.621407
4,105,1255,442,37,105,1,0,0.526035
5,100,1349,417,176,379,1,0,0.871407
...............

### Environment

botmot 

### Minimal Reproducible Example

python tracking/val.py --benchmark MOT17 --yolo-model pretrained/yolov8n.pt --reid-model pretrained/osnet_x0_25_msmt17.pt --tracking-method bytetrack --verbose --source tracking/val_utils/MOT17/train

**Comment by microchila** [comment]
<img width="437" alt="Snipaste_2024-08-16_16-32-44" src="https://github.com/user-attachments/assets/16e027fd-a193-4132-923d-5a0d0b15678d">
There seems to be a problem with the red box here

**Comment by mikel-brostrom** [comment]
frame index should start at one. Hence, `+1`. Some trackers have a tentative state. They need to be detected a few ties before they are accepted as valid tracks.

**Comment by microchila** [comment]
thanks!!!

**Comment by microchila** [comment]
By the way, why doesn't the id number reset correctly instead of picking up the id number from the previous video?Bytetrack @mikel-brostrom

**Comment by microchila** [comment]
> frame index should start at one. Hence, `+1`. Some trackers have a tentative state. They need to be detected a few times before they are accepted as valid tracks.

But in the function in the red box below, the +1 operation is done again and again
![image](https://github.com/user-attachments/assets/85409544-49e7-447c-8176-e7f40f8e4520)

**Comment by mikel-brostrom** [comment]
Ooooh, now I see. This is a big bug. Thanks for reporting @microchila

**Comment by microchila** [comment]
Author, after you change the last frame that way it's gone again.OVO

**Comment by mikel-brostrom** [comment]
What do you mean? Is it fixed?

**Comment by microchila** [comment]
No, it wasn't fixed correctly, on the contrary. After I ran MOT17-mini, the first clip was only 1~3 fps. gt had 4 fps. No more results for the last frame. I think it was caused by the outer function breaking early

**Comment by microchila** [comment]
The tracker is bytetrack, which should output the appropriate tracks at each frame

**Comment by mikel-brostrom** [comment]
I see. Tried this locally. Should be generating results for last frame as well 🚀 . Let me know

**Comment by mikel-brostrom** [comment]
Yup, major boosts now on metrics after the fixes.

**Comment by mikel-brostrom** [comment]
Now:

```bash
Format      Status❔  HOTA    MOTA    IDF1
Ocsort      ✅        25.635  8.0189  15.584
Bytetrack   ✅        25.819  8.0189  
Botsort     ✅        25.497  8.0189  15.584
Hybridsort  ✅        25.635  8.0189  15.584
Deepocsort  ✅        25.635 
Imprassoc   ✅        25.648  8.2547  15.983
```

Previously:

```bash
Format      Status❔  HOTA    MOTA    IDF1
Ocsort      ✅        21.684  6.6038  13.158
Bytetrack   ✅        21.717  6.6038  13.158
Botsort     ✅        21.61   6.6038  13158
Hybridsort  ✅        21.684  6.6038  13.158
Deepocsort  ✅        21.684  6.6038  13.158
```

**Comment by microchila** [comment]
Yes it worked but I was using COCO pre-trained yolov8n.pt and the metrics improved but not much
![image](https://github.com/user-attachments/assets/95b906e4-d3a1-4479-8504-235125674101)

**Comment by mikel-brostrom** [comment]
Great! Thank you again for reporting this bug @microchila
