### ISSUE TITLE
How to divide the MOT17 or MOT20 dataset?

### ISSUE THREAD

**Issue by microchila** [mikel-brostrom/boxmot#1580]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

For example, divide each video in the dataset into a front half and a back half?

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/boxmot/issues/1262#issuecomment-1898399022
