### ISSUE TITLE
more reid

### ISSUE THREAD

**Issue by microchila** [mikel-brostrom/boxmot#1581]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Is it possible to use some other reid model? For example, the reid models in BOTSORT that were trained in MOT17 and MOT20

**Comment by mikel-brostrom** [comment]
These models are not part of this repo but they could easily be added 😄. I don't have a timeline for this though

**Comment by microchila** [comment]
I tried it myself and added my own Reid model without success 😢...



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 20, 2024 18:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mikel-brostrom/boxmot] more reid (Issue #1581)




 
These models are not part of this repo but they could easily be added 😄. I don't have a timeline for this though

**Comment by mikel-brostrom** [comment]
1. Add the architecture to https://github.com/mikel-brostrom/boxmot/tree/master/boxmot/appearance/backbones
2. Add the URL to https://github.com/mikel-brostrom/boxmot/blob/4021f694892de03bf9152c060d79cc5d91d0a7fa/boxmot/appearance/reid_model_factory.py#L48C1-L51C100 with the following format `<model_name>-<dataset>.pt`

**Comment by yaoshanliang** [comment]
Can we use https://github.com/JDAI-CV/fast-reid as the reid repo?

**Comment by mikel-brostrom** [comment]
You can pass any embeddings to the trackers @yaoshanliang  😄
