### ISSUE TITLE
在一个非套接字尝试操作

### ISSUE THREAD

**Issue by microchila** [mikel-brostrom/boxmot#1583]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evaluation

### Bug

Running val.py twice in a row results in the following error, which is roughly caused by the fact that det_n_embs already exists

### Environment

boxmot

### Minimal Reproducible Example

Detections and Embeddings E:\boxmot\boxmot\runs\dets_n_embs\best\dets\MOT17-02-FRCNN.txt already existsudp_socket.close(). Overwrite? [y/N]: Traceback (most recent call last):
  File "E:\boxmot\boxmot\tracking\val.py", line 422, in <module>
    run_all(opt)
  File "E:\boxmot\boxmot\tracking\val.py", line 347, in run_all
    run_generate_dets_embs(opt)
  File "E:\boxmot\boxmot\tracking\val.py", line 285, in run_generate_dets_embs
    if prompt_overwrite('Detections and Embeddings', dets_path, opt.ci):
  File "E:\boxmot\boxmot\tracking\val.py", line 63, in prompt_overwrite
    return input_with_timeout(f"{path_type} {path} already existsudp_socket.close(). Overwrite? [y/N]: ")
  File "E:\boxmot\boxmot\tracking\val.py", line 55, in input_with_timeout
    inputs, _, _ = select.select([sys.stdin], [], [], timeout)
OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。

**Comment by mikel-brostrom** [comment]
Evaluation was never tested on windows. Now it should be fixed
