### ISSUE TITLE
new YOLO

### ISSUE THREAD

**Issue by microchila** [mikel-brostrom/boxmot#1587]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Will it be compatible with newer versions of the ultralytics framework (including YOLOV10) in the future?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
I will update the ultralytics package in the coming days such that the new model become available.

**Comment by microchila** [comment]
thanks

**Comment by mikel-brostrom** [comment]
Yolov8, v9 and v10 now available @microchila
