### ISSUE TITLE
what is α in the plot generated by trackeval？

### ISSUE THREAD

**Issue by microchila** [mikel-brostrom/boxmot#1588]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

What is the meaning of the abscissa α of the graph generated by running trackeval?
![image](https://github.com/user-attachments/assets/049ab9d1-9cac-445c-b6c9-35e83c9640f6)

**Comment by mikel-brostrom** [comment]
This is a question for `https://github.com/JonathonLuiten/TrackEval` which is the repo generating this file. I have never payed too much attention to this file
