### ISSUE TITLE
MOT20

### ISSUE THREAD

**Issue by microchila** [mikel-brostrom/boxmot#1591]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Can I ask if evaluating MOT20 only requires changing the MOT17 option to MOT20?

**Comment by mikel-brostrom** [comment]
Should be, yes. But let me know if it is not working 😄

**Comment by microchila** [comment]
It worked, and I'd also like to ask the author if he'll support evaluation operations for more datasets in future updates？BDD100K or KITTI tracking..... @mikel-brostrom

**Comment by mikel-brostrom** [comment]
I have no intention of supporting more datasets at the moment. But would be glad to review a PR for this 😄

**Comment by mikel-brostrom** [comment]
KITTI dataset also requires download from link sent to a registered email. So as far as I know it is not automatable.

**Comment by microchila** [comment]
Ask the user to put the dataset in a fixed format and then run the evaluation script if the framework supports it. If you can do that, thank you very much.


---Original---
From: ***@***.***&gt;
Date: Mon, Sep 9, 2024 16:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mikel-brostrom/boxmot] MOT20 (Issue #1591)




 
KITTI dataset also requires download from link sent to a registered email. So as far as I know it is not automatable.

**Comment by microchila** [comment]
> Ask the user to put the dataset in a fixed format and then run the evaluation script if the framework supports it. If you can do that, thank you very much.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Sep 9, 2024 16:15 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [mikel-brostrom/boxmot] MOT20 (Issue #1591) KITTI dataset also requires download from link sent to a registered email. So as far as I know it is not automatable. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

@mikel-brostrom

**Comment by microchila** [comment]
Ask the user to put the dataset in a fixed format and then run the evaluation script if the framework supports it. If you can do that, thank you very much.
@mikel-brostrom
