### ISSUE TITLE
Any suggestions for computation capabilities limited edge-device ?

### ISSUE THREAD

**Issue by kevin-wu822** [mikel-brostrom/boxmot#1595]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I've tried some ways to do MOT on a edge camera.
**Byte-Track:**  YOLOV8 is fast enough to do detect, but ID-switch happens easily only using the Kalman-filter.
**Bot-SORT:** It's not possible to get the ReID for everyone in the scene if you wanna reach a good fps.
Are there any other ways I can give it a try ?

**Comment by mikel-brostrom** [comment]
Which model are you using for the ReID part?

**Comment by kevin-wu822** [comment]
Let me start with some background：
I got a PTZ-camera and I wanna track someone (maybe the one in the middle of the first frame and we can change the target with a remote controller) . I retrained crowdhuman dataset using yolov8 to detect the head only, which took about 70ms per frame, and it worked good .
Firstly, I tried Byte-Track. But I found ID-switch happened easily when other walked pass the target within the association distance.
So I added the reid based on FastReID model. ( bagtricks_BOT_R50 on Market1501 Baselines: [)](https://github.com/JDAI-CV/fast-reid/blob/master/MODEL_ZOO.md), it took 14ms to get one person's ReID.  But I'm afraid that the fps will drop so much if there are too many people (even I use mobilenet ones)
I don't know how can I avoid the ID-switch problem as far as possible and keep a good frame rate for  my scenario ?

**Comment by mikel-brostrom** [comment]
The more objects to track the longer the time to generate the appearance embeddings and the association process to finish.

**Comment by mikel-brostrom** [comment]
If you are interested in a single object you can discard the rest of the tracked objects, lowering the computational load. This would require some custom modifications.

**Comment by mikel-brostrom** [comment]
You could use the bounding box prediction generated by the tracker for the specific object of interest, compare to it the rest for example by using IoU and finally discard the ones that do not overlap with it.

**Comment by kevin-wu822** [comment]
> The more objects to track the longer the time to generate the appearance embeddings and the association process to finish.

Yes,  I can discard the rest of the tracked objects. But how can I decide which ones to discard ?  I still need the ReID or Kalman filter Do you suggest OC-Sort (or some other without ReIDs ?) I haven't tried it . May it suit for my application ?

**Comment by mikel-brostrom** [comment]
Could be more suitable. The KF in OCSORT is designed for non-linear moving objects.

**Comment by mikel-brostrom** [comment]
> > The more objects to track the longer the time to generate the appearance embeddings and the association process to finish.
> 
> Yes, I can discard the rest of the tracked objects. But how can I decide which ones to discard ? I still need the ReID or Kalman filter Do you suggest OC-Sort (or some other without ReIDs ?) I haven't tried it . May it suit for my application ?

You are interested in a single object right?

**Comment by kevin-wu822** [comment]
> You could use the bounding box prediction generated by the tracker for the specific object of interest, compare to it the rest for example by using IoU and finally discard the ones that do not overlap with it.

I've thought about it.  it of course  discard some useless tracklets which we don't need to calculate the ReID feature. But people may gather together ( Who knows what the people will do ) I'll try OC-SORT, and any progress I'll let you know.  I'm now working  on it , and I'm interested in single object tracking .
