### ISSUE TITLE
weights obtained from the FastReid trained Strongsort BoT (with Resnet50 as the backbone) 

### ISSUE THREAD

**Issue by sunshinewxx** [mikel-brostrom/boxmot#1596]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Can the weights obtained from the FastReid trained Strongsort appearance extractor BagTracks (with Resnet50 as the backbone) be directly applied to the boxmot appearance for tracking performance metric calculation? Because BoT (Resnet50) also involves some other training techniques, such as BNNeck, while boxmot does not have relevant structures

**Comment by mikel-brostrom** [comment]
I would be more than glad to review this if somebody created a PR for it. I sadly don't have time right now to implement this.

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/boxmot/issues/1581#issuecomment-2298617133
