### ISSUE TITLE
已安装了tensorrt，提示还需要安装nvidia-tensorrt

### ISSUE THREAD

**Issue by xiaobai-python** [mikel-brostrom/boxmot#1597]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

运行环境：jetson orin nx、python3.8、cuda 11.4
问题：运行python3 tracking/track.py --source /workspace/test/track/person.mp4 --reid-model /data/box/models/osnet_x0_25_msmt17.engine，提示需要安装nvidia-tensorrt，但是我已经安装过tensorrt8.5.2.2
![1725006936035](https://github.com/user-attachments/assets/6e57955a-0e38-4f5f-b9a5-ed69f90821cd)

**Comment by xiaobai-python** [comment]
pt版本是有结果的

**Comment by mikel-brostrom** [comment]
Try with the recommended installations in the snapshot
