### ISSUE TITLE
Issues with supported trackers

### ISSUE THREAD

**Issue by microchila** [mikel-brostrom/boxmot#1601]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

In OCSORT,DEEP OCSORT,HybridSORT all use virtual trajectory update (ORU) as shown in the picture, but I don't see the related code in boxmot, why is that? 
![image](https://github.com/user-attachments/assets/24779a75-59eb-4699-acff-f45a9535dd09)

### Environment

BOXMOT

### Minimal Reproducible Example

![image](https://github.com/user-attachments/assets/c1510b59-90fa-4189-8f63-b99a81aef035)

**Comment by microchila** [comment]
It looks like they're both using the same Kalman filter .py file that defines the freezing code but doesn't use it.

**Comment by mikel-brostrom** [comment]
This looks like a major bug. Fixing.

**Comment by mikel-brostrom** [comment]
The fix is now merged!
