### ISSUE TITLE
Getting a ModuleNotFoundError 'tracking' despite installing everything in a virtualenv

### ISSUE THREAD

**Issue by sandip-meshh** [mikel-brostrom/boxmot#1606]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Running this on a RaspberryPi 4B 1GB, created a Python 3.10.14 virtualenv and pip installed boxmot as well as the poetry install with yolo from the installation page. I get the following error when I run the tracking code from the root directory inside the virtualenv:

```
Traceback (most recent call last):
  File "/home/meshh/code/boxmot/tracking/track.py", line 18, in <module>
    from tracking.detectors import get_yolo_inferer
ModuleNotFoundError: No module named 'tracking'
```
The same setup worked on my Macbook. Does the pipeline work on arm64 embedded platforms?

**Comment by mikel-brostrom** [comment]
Notice that it is not enough to install boxmot in you case. Check the README

**Comment by sandip-meshh** [comment]
Thanks for your quick reply @mikel-brostrom ! 

Not sure what I'm missing to be honest - I have followed all the steps mentioned below:
<img width="865" alt="image" src="https://github.com/user-attachments/assets/d00de634-7262-4748-810b-cd513b43727d">

**Comment by mikel-brostrom** [comment]
A pip installation of BoxMOT does not contain the tracking folder. You would need a full repo cloning for this:

```
git clone https://github.com/mikel-brostrom/boxmot.git
cd boxmot
pip install poetry
poetry install --with yolo  # installed boxmot + yolo dependencies
poetry shell  # activates the newly created environment with the installed dependencies
```

**Comment by sandip-meshh** [comment]
I did clone the full repo and ran all the above commands already in a pyenv-managed virtualenv. Not sure what I'm missing - need to review it again..

**Comment by sandip-meshh** [comment]
So, I ran the poetry install outside the virtualenv, using the `poetry env use 3.10` (my system Python version). The torch installation fails without any helpful description:

```bash
  - Installing torch (2.2.2+cu121): Failed

  RuntimeError

  Unable to find installation candidates for torch (2.2.2+cu121)

  at ~/.pyenv/versions/3.10.14/envs/cv-3.10/lib/python3.10/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│
       71│             links.append(link)
       72│
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│

Cannot install torch.
```
