### ISSUE TITLE
when i use a new yolov8s weight  gettted in my own dataset ,it gets an error

### ISSUE THREAD

**Issue by maoning123ab** [mikel-brostrom/boxmot#1607]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

![error](https://github.com/user-attachments/assets/03b3f871-9b36-47e3-b839-7862b5b83d04)

**Comment by ganyang0720** [comment]
py3.9

**Comment by mikel-brostrom** [comment]
I am not aware of this bug and cannot replicated it either... Do you mean this error arise from not using `python3.9` @ganyang0720
