### ISSUE TITLE
It seems that the Hybrid sort in the repo is not using the official hmiou?

### ISSUE THREAD

**Issue by wk565** [mikel-brostrom/boxmot#1626]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

<img width="222" alt="image" src="https://github.com/user-attachments/assets/52f5d151-07cf-4761-ae97-d5ed6d4b3018">
This is boxmot/utils/iou.py

**Comment by mikel-brostrom** [comment]
Should be integrated now:

https://github.com/mikel-brostrom/boxmot/commit/80eb43ef8241afd56a9e96224f19b17e8eef8163
