### ISSUE TITLE
can not run evolve.py 

### ISSUE THREAD

**Issue by wk565** [mikel-brostrom/boxmot#1652]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evolution

### Bug

When I run “python tracking/evolve.py --benchmark MOT17  --dets yolov8l --embs osnet_x0_25_msmt17 --n-trials 9 --tracking-method strongsort”，the error is：

Traceback (most recent call last):
  File "/home/xxx/CV/boxmot/tracking/evolve.py", line 137, in <module>
    opt.source = Path(opt.source).resolve()
  File "/home/xxx/anaconda3/envs/boxmot-new/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/xxx/anaconda3/envs/boxmot-new/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/xxx/anaconda3/envs/boxmot-new/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

### Environment

boxmot10.0.84, cuda11.3 , torch1.10, python03.9

### Minimal Reproducible Example

python tracking/evolve.py --benchmark MOT17 --dets yolov8l --embs osnet_x0_25_msmt17 --n-trials 9 --tracking-method strongsort

**Comment by mikel-brostrom** [comment]
Follow the syntax under evolution in README. You lack the `--source` arg

**Comment by wk565** [comment]
The instructions for evolve in the readme are:
# saves dets and embs under ./runs/dets_n_embs separately for each selected yolo and reid model
$ python tracking/generate_dets_n_embs.py --source ./assets/MOT17-mini/train --yolo-model yolov8n.pt yolov8s.pt --reid-model weights/osnet_x0_25_msmt17.pt
# evolve parameters for specified tracking method using the selected detections and embeddings generated in the previous step
$ python tracking/evolve.py --benchmark MOT17-mini --dets yolov8n --embs osnet_x0_25_msmt17 --n-trials 9 --tracking-method botsort

Among them, generate_dets_n_embs.py is no longer available in the current version. Can you update the readme?
