### ISSUE TITLE
benchmark evaluate

### ISSUE THREAD

**Issue by wk565** [mikel-brostrom/boxmot#1653]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello, Mikel, I noticed that you have updated the tracker table on your homepage. I would like to ask why you did not put the test results of hybridsort. I tried to test it myself on mot17-50 and found that the performance of hybrid was worse than other trackers, even not as good as bytetrack. Is there still some problem with the hybridsort code?

**Comment by mikel-brostrom** [comment]
`Hybridsort` fails in the pipeline as can be seen by its status. There is some issue with its compatibility with its KF.
