### ISSUE TITLE
Unable to reproduce the benchmark results in README

### ISSUE THREAD

**Issue by wk565** [mikel-brostrom/boxmot#1663]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I used python3 tracking/val.py --imgsz 320 --classes 0 --benchmark MOT17-50 --yolo-model yolov8x.pt --reid-model osnet_x1_0_dukemtmcreid.pt --tracking-method bytetrack --verbose --source ./tracking/val_utils/data/MOT17-50/train，but the performance is very poor, the detector you use in the readme is the official yolov8X without any trainning? 
The picture below is the performance results of bytetrack：
<img width="325" alt="image" src="https://github.com/user-attachments/assets/b1a7989e-ee55-4571-bded-dd96557c27a5">

**Comment by mikel-brostrom** [comment]
For reproducing the old results you can set `--conf 0.2`. For reproducing the new results, download the detections and emebedding + second half of MOT17 from here:

https://github.com/mikel-brostrom/boxmot/releases/tag/v10.0.83

**Comment by wk565** [comment]
> For reproducing the old results you can set `--conf 0.2`. For reproducing the new results, download the detections and emebedding + second half of MOT17 from here:
> 
> https://github.com/mikel-brostrom/boxmot/releases/tag/v10.0.83

Is the detector used by the detections and emebedding you provided ultralytics' default yolov8X, or has it been trained on some datasets?

**Comment by mikel-brostrom** [comment]
You can find the detections and embeddings used for the new results here:

https://drive.google.com/drive/folders/1zzzUROXYXt8NjxO1WUcwSzqD-nn7rPNr

As you can see the detector used is YoloX-x and the embedding come from BoT. For more details read the paper 😄

**Comment by wk565** [comment]
> You can find the detections and embeddings used for the new results here:
> 
> https://drive.google.com/drive/folders/1zzzUROXYXt8NjxO1WUcwSzqD-nn7rPNr
> 
> As you can see the detector used is YoloX-x and the embedding come from BoT. For more details read the paper 😄

Thanks，I thought it was the yolov8X's result，now I get it.
