### ISSUE TITLE
Demo on how to use MOT algorithms on colab

### ISSUE THREAD

**Issue by dnnxl** [mikel-brostrom/boxmot#1678]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi, I was wondering if there's a demo available for using MOT algorithms with YOLO. The notebook I found seems to be outdated.

**Comment by mikel-brostrom** [comment]
Colab notebook has now been updated!

**Comment by dnnxl** [comment]
Thanks!
