### ISSUE TITLE
Add onnxruntime-silicon , COREMLExecutionProvider to ONNXBackend 

### ISSUE THREAD

**Issue by ozayr** [mikel-brostrom/boxmot#1692]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

add support of silicon gpu by adding appropriate package and execution provider

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
Thanks for the enhancement proposal. I am on vacation right now, but I am creating a new release next Sunday.
