### ISSUE TITLE
  in strongsort about reid model(BOT)

### ISSUE THREAD

**Issue by xuani775** [mikel-brostrom/boxmot#1697]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I am trying to use the reid model in the original paper of strongsort and train it with the car Reid dataset. Refer to the following https://github.com/KaiyangZhou/deep-person-reid. However, it does not have the reid model of strongsort. How can I conduct  train.py(Especially the construction of the loss function)?

**Comment by mikel-brostrom** [comment]
You can find the code for BoT here: https://github.com/michuanhaohao/reid-strong-baseline

**Comment by xuani775** [comment]
Thank you. I have found Strongsort that about BOT. The author of Strongsort  adopted the BOT baseline in Fast Reid  from https://github.com/dyhBUPT/StrongSORT/issues/81

**Comment by mikel-brostrom** [comment]
Closing. This is now an enhancement task 😄
