### ISSUE TITLE
Ultralytics' YOLO11

### ISSUE THREAD

**Issue by davide-bontempelli-zupit** [mikel-brostrom/boxmot#1698]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Yolo11 has been released and it looks like is the new default for ultralytics. Are there plans to support it in boxmot? Thanks a lot for your work! 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by davide-bontempelli-zupit** [comment]
Btw I think that is a matter of updating the the ultralytics dependency and nothing more

**Comment by mikel-brostrom** [comment]
Now you can run:

`python3 tracking/track.py --yolo-model yolov11s --source 0 --show --tracking-method botsort`
