### ISSUE TITLE
When hybridsort can be fixed

### ISSUE THREAD

**Issue by wk565** [mikel-brostrom/boxmot#1699]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello MIkel, I want to know when hybridsort can be fixed.

**Comment by mikel-brostrom** [comment]
It is in my backlog but right now I do not have time to look into this

**Comment by mikel-brostrom** [comment]
It should be fairly easy though. The KF has to be fixed to take into cinsideration the confidence of the detetion
