### ISSUE TITLE
Tracker parameters

### ISSUE THREAD

**Issue by MorningHero92** [mikel-brostrom/boxmot#1700]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Sorry dear sir, I've tried to fine-tune botsort tracker by changing settings in botsort.py and botsort.yaml files but there's no changes. By settings i mean things like proximity threshold, track buffer and so on. How should I do it?

**Comment by mikel-brostrom** [comment]
I recommend you to collect a small dataset in order to fine-tune the tracker.
