### ISSUE TITLE
Roadmap for boxmot

### ISSUE THREAD

**Issue by davide-bontempelli-zupit** [mikel-brostrom/boxmot#1706]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi Mikel, do you have a roadmap for this project?
E.g. algorithms to implement/improve or new evaluations, etc?

If so you could put it in the readme or create a project here in on github

Thanks for your work :)

**Comment by mikel-brostrom** [comment]
https://github.com/users/mikel-brostrom/projects/2

However, I am quite busy at the moment. So there are no specific release time for any of these features

**Comment by mikel-brostrom** [comment]
Feel free to grab any of these 😄

**Comment by davide-bontempelli-zupit** [comment]
Thanks!
