### ISSUE TITLE
AttributeError: 'StrongSort' object has no attribute 'plot_results'

### ISSUE THREAD

**Issue by yuzhouzhili** [mikel-brostrom/boxmot#1728]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Other

### Bug

AttributeError: 'StrongSort' object has no attribute 'plot_results' on master branch

### Environment

 boxmot.utils.torch_utils:select_device:52 - Yolo Tracking v11.0.5 🚀 Python-3.9.13 torch-2.2.2+cu121

### Minimal Reproducible Example

AttributeError: 'StrongSort' object has no attribute 'plot_results'

**Comment by davide-bontempelli-zupit** [comment]
Same as https://github.com/mikel-brostrom/boxmot/issues/1525

As reported there:

> Is it because it is not extending the BaseTracker class [here](https://github.com/mikel-brostrom/boxmot/blob/ff548d59de9236ce04c989b91d5c680a45b14abf/boxmot/trackers/strongsort/strong_sort.py#L14C18-L14C24)?

**Comment by shmy12** [comment]
Just change StongSort to not display the tracking results, as shown below：

   for r in results:

        # img = yolo.predictor.trackers[0].plot_results(r.orig_img, args.show_trajectories)
        #
        # if args.show is True:
        #     cv2.imshow('BoxMOT', img)
        #     key = cv2.waitKey(1) & 0xFF
        #     if key == ord(' ') or key == ord('q'):
        #         break
        img = None
