### ISSUE TITLE
Evaluate trackers using only needed dataset and its part

### ISSUE THREAD

**Issue by Fleyderer** [mikel-brostrom/boxmot#1732]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

By now, `val.py` has options `--source` and `--split`, which are not used during generating MOT results in `generate_mot_results` function.

Instead, we have:
```
for y in opt.yolo_model:
        exp_folder_path = opt.project / 'mot' / (str(y.stem) + "_" + str(opt.reid_model[0].stem) + "_" + str(opt.tracking_method))
        exp_folder_path = increment_path(path=exp_folder_path, sep="_", exist_ok=False)
        opt.exp_folder_path = exp_folder_path
        dets_file_paths = [item for item in (opt.project / "dets_n_embs" / y.stem / 'dets').glob('*.txt') if not item.name.startswith('.')]
        embs_file_paths = [item for item in (opt.project / "dets_n_embs" / y.stem / 'embs' / opt.reid_model[0].stem).glob('*.txt') if not item.name.startswith('.')]
        for d, e in zip(dets_file_paths, embs_file_paths):
```

where `d` and `e` are **all** dets and embs already calculated for current (detector, embeddor) pair.

This leads to wrong behaviour, for example, after this command:

```
python tracking/val.py --benchmark MOT17 --yolo-model yolo11x.pt --tracking-method botsort --reid-model osnet_x0_25_msmt17.pt  --source tracking/val_utils/data/MOT17/test
```

As a result I will have metrics not only for  MOT17-train and MOT17-test together (instead test only), but also for MOT20 and every another pre-calculated pairs of (dets, embs). 

So in my opinion, this behaviour is unexpected and not intuitive, and also doesn't make sense since we want to compare results only on test part of specific dataset, which can be from another domain, with needed augmentations etc.

If you are interested, I will make pull request with fix, using information passed to `--source` parameter.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
Sounds good. I am mostly focusing on working with pre-generated detections and embeddings so I have not given this to much importance. But feel free to leave a PR. Will be more than happy to check it out 😄
