### ISSUE TITLE
Remove benchmark and split options from evauation

### ISSUE THREAD

**Issue by Fleyderer** [mikel-brostrom/boxmot#1741]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

##  How it works now

We have `--benchmark` and `--split` options, which should be passed together with the `--source` parameter, where we already have `.../<benchmark>/<split>` inside the path. 

## How it will work:
```
benchmark = Path(opt.source).name
split = Path(opt.source).parent
```

And of cource this info should be reflected in log.

I have tried to avoid this change, but I am tired of this unexpected behaviour when I pass `.../MOT17/test` as the source and somehow script is yelling at me that he can't find file from test or something else :smiley: 

I decided to know your opinion before changing, these options are used only in `val.py` file

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
I agree. It is confusing. Let's only keep source and extract the benchmark from the source path itself?

**Comment by mikel-brostrom** [comment]
this got fixed here: https://github.com/mikel-brostrom/boxmot/pull/1746
