### ISSUE TITLE
Is that possible we could support TensorRT 10?

### ISSUE THREAD

**Issue by tjvvai** [mikel-brostrom/boxmot#1748]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Hi, thank you so much for the new image to support yolov10. That's very helpful and saves us a lot of efforts to do the adaption from previous versions.

As yolov11 already supports trt10 in its code base, I was wondering whether we could do the same to be compatible with trt10 and below simultaneously. 

Try to deploy on Jetson Nano Orin, but we have to rewrite some code to support that as the code is based on trt8.  

So wondering whether possible to integrate that feature into the pipeline.

Thanks in advance

### Use case

people who try to deploy the pipeline on edge devices like Jetson.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
I do not own a machine with an Nvidia GPU at the moment. So I cannot debug this functionality but I made an update to this backend so try it out 😄

**Comment by mikel-brostrom** [comment]
If you encounter issues and you make it work, please copy paste the solution here 🚀

**Comment by tjvvai** [comment]
Thank you so much for your prompt reply. 

I have checked the latest Commit e576cdb, but not sure it is trt10 compatible.

I will try to make it work with trt10. Once it works, I will paste it over here.

Thanks again!
