### ISSUE TITLE
Poor performance on people detection

### ISSUE THREAD

**Issue by sandip-meshh** [mikel-brostrom/boxmot#1755]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I'm using Boxmot v11.0.6 to detect the number of people in a frame. I've reduced the resolution to 640x480 and the FPS to 15 to reduce bandwidth of the network stream. I observe very poor detection accuracy in my initial tests. Admittedly, the camera is placed > 20m from the subjects. 

Are there any tuning parameters that can increase detection accuracy for this setup?

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/b9bb388b-1a60-4e5c-b810-e2b000472014">

**Comment by mikel-brostrom** [comment]
Which object detector are you using?

**Comment by sandip-meshh** [comment]
The default one - yolov8n.
