### ISSUE TITLE
can boxmot run on macos?

### ISSUE THREAD

**Issue by dyhgo** [mikel-brostrom/boxmot#1756]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

can boxmot run on macos?

**Comment by mikel-brostrom** [comment]
Absolutely,

# Initialize the tracker
tracker = BotSort(
    reid_weights=Path('osnet_x0_25_msmt17.pt'),  # Path to ReID model
    device=torch.device('mps'),  # Use CPU for inference
    half=False
)

**Comment by dyhgo** [comment]
thank you!
