### ISSUE TITLE
low metrics when eval

### ISSUE THREAD

**Issue by dyhgo** [mikel-brostrom/boxmot#1758]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I execute the default command "python3 tracking/val.py --yolo-model yolov10x --reid-model osnet_x0_25_msmt17.pt --tracking-method botsort     --verbose --source ./tracking/val_utils/MOT17/train". But the metric results are low, like {"HOTA": 25.661, "MOTA": 18.76, "IDF1": 22.929}. the problem seems to be that poor performance of yolov10x on MOT17. why is that ?

**Comment by dyhgo** [comment]
i use default yolov10x as detector, it perform good on MOT17-9 (big objects) but perform bad on MOT17-13 (many small objects)

**Comment by mikel-brostrom** [comment]
The results displayed under README are generated using the detections generated by a Yolox-X model, the same as in the bytetrack paper

**Comment by dyhgo** [comment]
I read the paper, the detector is Yolox-X trained on CrowdHuman and half training set of MOT17. Do you have trained weights of Yolox-X

**Comment by zhaojunzhe123** [comment]
yolox ran but an error was reported as follows:  
 from boxmot.utils.ops import yolox_preprocess
ImportError: cannot import name 'yolox_preprocess' from 'boxmot.utils.ops' (/opt/anaconda3/envs/zjz_boxmot/lib/python3.9/site-packages/boxmot/utils/ops.py)
ERROR conda.cli.main_run:execute(124): `conda run python /home/zjz/Project/models/boxmot/tracking/val.py --yolo-model yolox_m.pth --reid-model /home/zjz/Project/models/boxmot/resnet50_msmt17.pth --tracking-method deepocsort --verbose --source /home/zjz/Project/models/boxmot/assets/MOT17-mini/train` failed. (See above for error)
