### ISSUE TITLE
object detection conf threshold setting

### ISSUE THREAD

**Issue by siri-rouser** [mikel-brostrom/boxmot#1761]
### Question

Hi, 
I am using a command like this:
python track.py --yolo-model yolov10x --tracking-method deepocsort --conf 0.3 --iou 0.3 --reid-model clip_vehicleid.pt --classes 2 5 7 --source /home/yuqiang/yl4300/project/boxmot/NvRec_18/segment_4.mp4 

but i find that the result only output conf threshold >0.5 object and can't detect the object lower than this threshold? 

can you help me dealing with this? Thanks

**Comment by mikel-brostrom** [comment]
Notice that DeepCOSort has its own detection threshold:

https://github.com/mikel-brostrom/boxmot/blob/90132fc903ceecda051ccf49b7d38474a7eab98e/boxmot/configs/deepocsort.yaml#L3

**Comment by siri-rouser** [comment]
Thanks! That solves the problem
