### ISSUE TITLE
Low evaluation of custom data sets and storage path problems

### ISSUE THREAD

**Issue by wx-ikll007700** [mikel-brostrom/boxmot#1764]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello, I am very interested in your project. I found my own data set and tried it. My data set has only one category. I trained my own detection weight (marked with gt file). After I ran val.py, I found that the results of bytetrack were all 0, and the results of deepocsort and botsort were the same, and they were very low. I felt that the detector did not work, but both my folders were generated.
![微信图片_20241205210640](https://github.com/user-attachments/assets/540acfe0-b52a-4805-9cee-fad84e051f8c)
![微信图片_20241205210708](https://github.com/user-attachments/assets/5827a3ed-636a-4517-8f4f-c82734fcdb88)

**Comment by wx-ikll007700** [comment]
According to the results, my gt file should have been detected, but my detector doesn't seem to have detected my data.

**Comment by wx-ikll007700** [comment]
According to the results, my gt file should have been detected, but my detector doesn't seem to have detected my data.When I use bytetrack, the results are all 0, and the results of deepocsort and botsort are the same but extremely low.

**Comment by lmaple24327** [comment]
Hello, at present, I am also using YOLOv8 and BOTSORT for target tracking, and I also use my own custom data set, but the evaluation effect is also very poor. May I ask how do you use OCSORT? Do you use this program with many warehouses?

> 根据结果，我的 gt 文件应该已经被检测到，但我的检测器似乎没有检测到我的数据。当我使用 bytetrack 时，结果都是 0，deepocsort 和 botsort 的结果相同但极低。

**Comment by wx-ikll007700** [comment]
> Hello, at present, I am also using YOLOv8 and BOTSORT for target tracking, and I also use my own custom data set, but the evaluation effect is also very poor. May I ask how do you use OCSORT? Do you use this program with many warehouses?
> 
> > 根据结果，我的 gt 文件应该已经被检测到，但我的检测器似乎没有检测到我的数据。当我使用 bytetrack 时，结果都是 0，deepocsort 和 botsort 的结果相同但极低。

Isn't this boxmot integrated with many tracking algorithms, and it only needs to be selected in the instruction, but my effect is very poor. It seems that I didn't put the path of the file right. Did you deploy it with this boxmot?

**Comment by 14790897** [comment]
I feel the same way. I think this document is very vague, and I don't know exactly how to run the evaluation. Also, I am evaluating on my own training dataset.
```
All sequences for  finished in 0.72 seconds

HOTA: -pedestrian                  HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
mot_particle                       36.257    30.554    44.278    36.564    44.857    48.719    60.939    67.89     40.074    81.835    45.642    37.351
COMBINED                           36.257    30.554    44.278    36.564    44.857    48.719    60.939    67.89     40.074    81.835    45.642    37.351

CLEAR: -pedestrian                 MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
mot_particle                       -18.079   67.756    -18.016   31.748    38.949    3.6364    54.545    41.818    -28.316   1008      2167      1580      2         2         30        23        153
COMBINED                           -18.079   67.756    -18.016   31.748    38.949    3.6364    54.545    41.818    -28.316   1008      2167      1580      2         2         30        23        153

Identity: -pedestrian              IDF1      IDR       IDP       IDTP      IDFN      IDFP
mot_particle                       34.669    31.465    38.601    999       2176      1589
COMBINED                           34.669    31.465    38.601    999       2176      1589

Count: -pedestrian                 Dets      GT_Dets   IDs       GT_IDs
mot_particle                       2588      3175      55        55
COMBINED                           2588      3175      55        55
```

**Comment by mikel-brostrom** [comment]
> I think this document is very vague, and I don't know exactly how to run the evaluation.

You clearly managed to run an evaluation. Regarding you negative MOTA: https://github.com/mikel-brostrom/boxmot/issues/938

**Comment by wx-ikll007700** [comment]
> I feel the same way. I think this document is very vague, and I don't know exactly how to run the evaluation. Also, I am evaluating on my own training dataset.
> 
> ```
> All sequences for  finished in 0.72 seconds
> 
> HOTA: -pedestrian                  HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
> mot_particle                       36.257    30.554    44.278    36.564    44.857    48.719    60.939    67.89     40.074    81.835    45.642    37.351
> COMBINED                           36.257    30.554    44.278    36.564    44.857    48.719    60.939    67.89     40.074    81.835    45.642    37.351
> 
> CLEAR: -pedestrian                 MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
> mot_particle                       -18.079   67.756    -18.016   31.748    38.949    3.6364    54.545    41.818    -28.316   1008      2167      1580      2         2         30        23        153
> COMBINED                           -18.079   67.756    -18.016   31.748    38.949    3.6364    54.545    41.818    -28.316   1008      2167      1580      2         2         30        23        153
> 
> Identity: -pedestrian              IDF1      IDR       IDP       IDTP      IDFN      IDFP
> mot_particle                       34.669    31.465    38.601    999       2176      1589
> COMBINED                           34.669    31.465    38.601    999       2176      1589
> 
> Count: -pedestrian                 Dets      GT_Dets   IDs       GT_IDs
> mot_particle                       2588      3175      55        55
> COMBINED                           2588      3175      55        55
> ```

I feel that your evaluation process is normal, but the accuracy is low. It may be that the text you used for evaluation is not set properly.
