### ISSUE TITLE
How are your models trained and evaluated using MOT17?

### ISSUE THREAD

**Issue by Keqi19** [mikel-brostrom/boxmot#1778]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

How are your models trained and evaluated using MOT17?

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/boxmot/blob/master/.github/workflows/benchmark.yml

**Comment by mikel-brostrom** [comment]
Short summary. [trackeval](https://github.com/JonathonLuiten/TrackEval) is used for evaluating the generated tracks and compare them to the gt tracks
